# DIABETES WORKFLOW

## Data-Preprocessing

Import diabetes data set

In [4]:
import pandas as pd

In [5]:
diabetes = pd.read_csv("diabetes_prediction_dataset.csv")

## Data Wrangling
Checked the data for na and null values. Also filtered data sets by women and by age groups 18 and under, 19-30, 31-45, and 45 and above

In [6]:
diabetes_women = diabetes.query('gender == "Female"')
diabetes = diabetes_women.sort_values("age",ascending=True)

There is no na values

In [8]:
diabetes_women.isna().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

There is no null values

In [9]:
diabetes_women.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

Filtering by age groups 18 and under

In [35]:
diabetes_w_18 = diabetes_women.query('age <= 18.0')
diabetes_w_18.sort_values("age",ascending=True)
#diabetes_w_18["age"].unique()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
155,Female,0.08,0,0,No Info,14.43,6.5,160,0
57276,Female,0.08,0,0,No Info,27.32,3.5,130,0
57655,Female,0.08,0,0,No Info,12.82,3.5,90,0
48070,Female,0.08,0,0,No Info,12.22,3.5,130,0
46033,Female,0.08,0,0,No Info,14.10,5.0,160,0
...,...,...,...,...,...,...,...,...,...
60918,Female,18.00,0,0,never,24.96,6.6,85,0
60904,Female,18.00,0,0,No Info,23.43,5.0,158,0
288,Female,18.00,0,0,never,19.60,3.5,140,0
681,Female,18.00,0,0,not current,27.32,6.6,85,0
22713,Female,18.00,0,0,No Info,27.32,5.8,155,0

Create dataset with age group 19-30

In [34]:
diabetes_w_19_30 = diabetes_women.query('age <= 20 and age >=19')
diabetes_w_19_30.sort_values("age",ascending=True)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99420,Female,19.0,0,0,never,27.32,6.6,155,0
99282,Female,19.0,0,0,No Info,23.68,4.8,160,0
99200,Female,19.0,0,0,never,20.03,6.2,158,0
99187,Female,19.0,0,0,No Info,31.84,6.6,145,0
99097,Female,19.0,0,0,not current,19.16,6.6,158,0
...,...,...,...,...,...,...,...,...,...
33,Female,20.0,0,0,never,22.19,3.5,100,0
99781,Female,20.0,0,0,never,24.84,6.0,130,0
99893,Female,20.0,0,0,current,28.06,6.0,80,0
99917,Female,20.0,0,0,never,27.32,5.8,158,0
5,Female,20.0,0,0,never,27.32,6.6,85,0

Filter to age group 30 -45

In [33]:
diabetes_w_31_45 = diabetes_women.query('age <= 45 and age >=31')
diabetes_w_31_45.sort_values("age",ascending=True)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99802,Female,31.0,0,0,No Info,30.89,5.0,160,0
70595,Female,31.0,0,0,No Info,30.56,5.7,140,0
21321,Female,31.0,0,0,former,29.23,4.0,130,0
94388,Female,31.0,0,0,No Info,27.32,4.0,126,0
7296,Female,31.0,0,0,never,40.14,4.5,158,0
...,...,...,...,...,...,...,...,...,...
85220,Female,45.0,0,0,never,33.15,5.0,140,0
85231,Female,45.0,0,0,current,27.32,5.7,100,0
99686,Female,45.0,0,0,No Info,32.73,5.7,145,0
99967,Female,45.0,0,0,former,32.81,4.5,145,0
58322,Female,45.0,0,0,No Info,27.32,6.1,126,0

Fitler to age group 46 and older

In [32]:
diabetes_w_46= diabetes_women.query('age >=46')
diabetes_w_46.sort_values("age",ascending=True)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
94593,Female,46.0,0,0,never,27.32,5.0,158,0
14784,Female,46.0,1,0,current,34.99,5.0,200,0
69518,Female,46.0,0,0,current,25.03,6.0,159,0
69658,Female,46.0,0,0,former,23.63,3.5,200,0
69609,Female,46.0,0,0,never,31.25,6.6,80,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
140,Female,80.0,1,0,never,44.06,6.5,160,0
0,Female,80.0,0,1,never,25.19,6.6,140,0
99947,Female,80.0,0,0,former,27.32,6.6,155,0
99922,Female,80.0,0,0,not current,27.32,6.6,85,0